### ENDPOINT TO FETCH X RANDOMS WORDS of 5 letters length from external api 
### https://random-word-api.herokuapp.com/word?length=5&number=
GET http://localhost:3000/save-file

### ENDPOINT TO INITIALIZE WORDLE GAME
GET http://localhost:3000/start

### RESPONSE
# {
#   "number": 4,
#   "token": "f84e14d2-3bbd-4d55-aa3b-ed78b3156720"
# }

### RETURNS SECRET WORD CHOSEN RANDOMLY
GET http://localhost:3000/secret-word/05e85f91-a753-4d49-9ea6-82462b4cce2e

# RESPONSE EX.: spunk
###

### ENDPOINT TO PLAY WORDLE
GET http://localhost:3000/05e85f91-a753-4d49-9ea6-82462b4cce2e/guess/spunk
### 
# value = 1, "Correct" letter
# value = 2, "Present" letter
# value = 3, "Absent"  letter 

### RESPONSE, WHEN THE GUESSED WORD IS WRONG AND COUNTER IS LESS THAN 5
# {
#   "statusGame": "Try-Again",
#   "intent": "pingo",
#   "statusLetter": [
#     {
#       "letter": "p",
#       "value": 1
#     },
#     {
#       "letter": "i",
#       "value": 3
#     },
#     {
#       "letter": "n",
#       "value": 3
#     },
#     {
#       "letter": "g",
#       "value": 3
#     },
#     {
#       "letter": "o",
#       "value": 2
#     }
#   ],
#   "counter": 2
# }

### RESPONSE WHEN SUCCESSFULLY GUESSED AND COUNTER IS LESS THAN 5
# {
#   "statusGame": "Win",
#   "intent": "spunk",
#   "statusLetter": [
#     {
#       "letter": "s",
#       "value": 1
#     },
#     {
#       "letter": "p",
#       "value": 1
#     },
#     {
#       "letter": "u",
#       "value": 1
#     },
#     {
#       "letter": "n",
#       "value": 1
#     },
#     {
#       "letter": "k",
#       "value": 1
#     }
#   ],
#   "counter": 1,
#   "secretWord": "spunk",
#   "gamesWon": 2
# }


